# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jon Q | Designer & Doodler
description: > # this means to ignore newlines until "baseurl:"
  Heya! I'm a Toronto designer who loves beautifully engineered CSS & doodles.

# Build settings
markdown: kramdown


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

gems:
- jekyll-assets


assets:
  compress:
    css: true
  cache: .asset-cache
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor
  features:
    liquid: true
    automatic_img_alt: false


exclude: ["bower_components", "tmp", "node_modules", ".tmp", ".grunt", ".asset-cache", "_assets/vendor"]
